# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VirtualMachineSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 434)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.leVerifyPassword = QtWidgets.QLineEdit(Dialog)
        self.leVerifyPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leVerifyPassword.setObjectName("leVerifyPassword")
        self.gridLayout.addWidget(self.leVerifyPassword, 11, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 12, 1, 1, 2)
        self.leComment = QtWidgets.QLineEdit(Dialog)
        self.leComment.setObjectName("leComment")
        self.gridLayout.addWidget(self.leComment, 1, 1, 1, 1)
        self.chkVmware = QtWidgets.QCheckBox(Dialog)
        self.chkVmware.setObjectName("chkVmware")
        self.gridLayout.addWidget(self.chkVmware, 1, 2, 1, 1)
        self.leCpus = QtWidgets.QLineEdit(Dialog)
        self.leCpus.setObjectName("leCpus")
        self.gridLayout.addWidget(self.leCpus, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.leMemSize = QtWidgets.QLineEdit(Dialog)
        self.leMemSize.setObjectName("leMemSize")
        self.gridLayout.addWidget(self.leMemSize, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 2)
        self.leDiskSize = QtWidgets.QLineEdit(Dialog)
        self.leDiskSize.setObjectName("leDiskSize")
        self.gridLayout.addWidget(self.leDiskSize, 7, 1, 1, 1)
        self.lePassword = QtWidgets.QLineEdit(Dialog)
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.gridLayout.addWidget(self.lePassword, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.leIsoPath = QtWidgets.QLineEdit(Dialog)
        self.leIsoPath.setObjectName("leIsoPath")
        self.gridLayout.addWidget(self.leIsoPath, 8, 1, 1, 1)
        self.leVmName = QtWidgets.QLineEdit(Dialog)
        self.leVmName.setObjectName("leVmName")
        self.gridLayout.addWidget(self.leVmName, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 1)
        self.leUser = QtWidgets.QLineEdit(Dialog)
        self.leUser.setObjectName("leUser")
        self.gridLayout.addWidget(self.leUser, 9, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.leIsoUrl = QtWidgets.QLineEdit(Dialog)
        self.leIsoUrl.setObjectName("leIsoUrl")
        self.gridLayout.addWidget(self.leIsoUrl, 2, 1, 1, 1)
        self.leIsoHash = QtWidgets.QLineEdit(Dialog)
        self.leIsoHash.setObjectName("leIsoHash")
        self.gridLayout.addWidget(self.leIsoHash, 3, 1, 1, 1)
        self.chkVbox = QtWidgets.QCheckBox(Dialog)
        self.chkVbox.setObjectName("chkVbox")
        self.gridLayout.addWidget(self.chkVbox, 2, 2, 1, 1)
        self.chkParallels = QtWidgets.QCheckBox(Dialog)
        self.chkParallels.setObjectName("chkParallels")
        self.gridLayout.addWidget(self.chkParallels, 3, 2, 1, 1)
        self.chkVagrant = QtWidgets.QCheckBox(Dialog)
        self.chkVagrant.setObjectName("chkVagrant")
        self.gridLayout.addWidget(self.chkVagrant, 4, 2, 1, 1)
        self.chkDesktop = QtWidgets.QCheckBox(Dialog)
        self.chkDesktop.setObjectName("chkDesktop")
        self.gridLayout.addWidget(self.chkDesktop, 5, 2, 1, 1)
        self.chkUpdate = QtWidgets.QCheckBox(Dialog)
        self.chkUpdate.setObjectName("chkUpdate")
        self.gridLayout.addWidget(self.chkUpdate, 6, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.leComment, self.leIsoUrl)
        Dialog.setTabOrder(self.leIsoUrl, self.leIsoHash)
        Dialog.setTabOrder(self.leIsoHash, self.leVmName)
        Dialog.setTabOrder(self.leVmName, self.leCpus)
        Dialog.setTabOrder(self.leCpus, self.leMemSize)
        Dialog.setTabOrder(self.leMemSize, self.leDiskSize)
        Dialog.setTabOrder(self.leDiskSize, self.leIsoPath)
        Dialog.setTabOrder(self.leIsoPath, self.leUser)
        Dialog.setTabOrder(self.leUser, self.lePassword)
        Dialog.setTabOrder(self.lePassword, self.leVerifyPassword)
        Dialog.setTabOrder(self.leVerifyPassword, self.chkVmware)
        Dialog.setTabOrder(self.chkVmware, self.chkVbox)
        Dialog.setTabOrder(self.chkVbox, self.chkParallels)
        Dialog.setTabOrder(self.chkParallels, self.chkVagrant)
        Dialog.setTabOrder(self.chkVagrant, self.chkDesktop)
        Dialog.setTabOrder(self.chkDesktop, self.chkUpdate)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Virtual Machine Settings"))
        self.label_9.setText(_translate("Dialog", "Iso url"))
        self.chkVmware.setText(_translate("Dialog", "VmWare Image"))
        self.label.setText(_translate("Dialog", "Comment"))
        self.label_2.setText(_translate("Dialog", "VM Name"))
        self.label_4.setText(_translate("Dialog", "CPUs"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>Virtual Machine Settings</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "Verify Password"))
        self.label_13.setText(_translate("Dialog", "Memory Size"))
        self.label_5.setText(_translate("Dialog", "Disk Size"))
        self.label_7.setText(_translate("Dialog", "Ssh Password"))
        self.label_3.setText(_translate("Dialog", "Iso Path"))
        self.label_6.setText(_translate("Dialog", "Ssh User"))
        self.label_10.setText(_translate("Dialog", "Iso Hash"))
        self.chkVbox.setText(_translate("Dialog", "VirtualBox Image"))
        self.chkParallels.setText(_translate("Dialog", "Parallels Image"))
        self.chkVagrant.setText(_translate("Dialog", "Vagrant Box"))
        self.chkDesktop.setText(_translate("Dialog", "Desktop"))
        self.chkUpdate.setText(_translate("Dialog", "Updates"))

